config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/passkey_sessions'
  }

  devise_scope :user do
    post 'sign_up/new_challenge', to: 'users/registrations#new_challenge', as: :new_user_registration_challenge
    post 'sign_in/new_challenge', to: 'users/passkey_sessions#new_challenge', as: :new_user_session_challenge

    post 'reauthenticate/new_challenge', to: 'users/passkey_reauthentication#new_challenge', as: :new_user_reauthentication_challenge
    post 'reauthenticate', to: 'users/passkey_reauthentication#reauthenticate', as: :user_reauthentication


    get '/emergency_passkey_registration/', to: 'users/emergency_passkey_registrations#edit', as: :emergency_passkey_registration
    patch '/emergency_passkey_registration/', to: 'users/emergency_passkey_registrations#update'
    put '/emergency_passkey_registration/', to: 'users/emergency_passkey_registrations#update'

    resources :emergency_passkey_registrations, controller: "users/emergency_passkey_registrations", only: [:new, :create] do
      collection do
        post :new_challenge
      end
    end

    namespace :users do
      resources :passkeys, only: [:create, :destroy] do
        collection do
          post :new_create_challenge
        end

        member do
          post :new_destroy_challenge
        end
      end
    end
  end


  root "root#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/helpers/root_helper.rb
module RootHelper
end

app/views/root/index.html.erb
<h1>Root#index</h1>

<%= render "devise/shared/links", resource_name: :user, devise_mapping: Devise.mappings[:user] %>

<h2>User details</h2>

<%= link_to "Edit User", edit_registration_path(current_user) %>

<code>
<%= current_user.email %>
<%= current_user.webauthn_id %>
</code>

<h3>Passkeys</h3>

<table>
  <thead>
    <tr>
      <th>Label</th><th>Sign Count</th><th>Last Used At</th><th>Public Key</th><th>External ID</th><th></th>
    </tr>
  </thead>
  <tbody>
  <% current_user.passkeys.each do |passkey| %>
    <tr>
      <td><%= passkey.label %></td>
      <td><%= passkey.sign_count %></td>
      <td><%= passkey.last_used_at %></td>
      <td><pre><%= passkey.public_key %></pre></td>
      <td><pre><%= passkey.external_id %></pre></td>
      <td>
        <% if current_user.passkeys.count > 1 %>
          <%= form_with(
            model: [:users, passkey],
            method: :delete,
            class: "delete-passkey",
            data: {
              "reauthentication_challenge_url": new_destroy_challenge_users_passkey_url(passkey),
              "reauthentication_token_url": user_reauthentication_url,
              "reauthentication_token_field_name": "passkey[reauthentication_token]",
            }
          ) do |f| %>
            <%= f.hidden_field :reauthentication_token %>
            <button type="submit"><%= image_tag("passkey-black.svg", width: "25", height: "25") %>Delete</button>
          <% end %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= render "users/passkeys/new_form", resource_name: :user %>


<script type="module">
  import {getReauthenticationToken} from 'passkey_reauthentication_handler'

  let submitDeletePasskeyFormEvent = async function(event){
    event.preventDefault()
    event.stopImmediatePropagation()
    let form = event.currentTarget
    await getReauthenticationToken(form)
    form.submit()
  }

  document.querySelectorAll('.delete-passkey').forEach(form => form.addEventListener('submit', submitDeletePasskeyFormEvent))
</script>